# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'tasks' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tasks

	pod 'Firebase/Core'
	pod 'FirebaseUI'
	pod 'Firebase/Firestore'

  target 'tasksTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tasksUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
